#!/usr/bin/bash

if [[ $# -eq 0 ]] ; then
    echo "Error: Please pass the command you want to benchmark."
    echo "********************************************************"
    echo -e "Usage: \n\t $0 <cmd_to_benchmark>"
    echo "********************************************************"
    exit 0
fi

echo "Benchmarking:"
echo $*

sudo cpupower monitor -c $* > cstates.txt &
PID1=$!

sudo perf stat -a --per-socket -I 1000 -e power/energy-pkg/ 2> power_usage.txt &
PID2=$!

sudo trace-cmd record -e sched_wakeup > /dev/null &
PID3=$!

# Wait for the benchmark to end
wait $PID1

# Send Ctrl + c or SIGINT to perf and trace-cmd
kill -SIGINT $PID2
kill -SIGINT $PID3

# Wait until perf and trace-cmd finish
wait $PID2
wait $PID3

# Summarize the results
echo -e "\nCStates:"
cat cstates.txt
more cstates.txt | grep "||  " | awk -v N=`nproc` -f summarize_cstates.awk

echo -e "\nEnergy Consumed:"
cat power_usage.txt | tail -n +2 | awk '{s+=$4} END {print s " J"}'

echo -e "\nPer CPU wakeups:"
trace-cmd report > report.txt
grep "sched_wakeup" report.txt | awk -f count_cpu.awk | sort
